# Generated by Django 5.1.4 on 2024-12-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
